name: comp_alchemy_notebook
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - pip
  - ase
  - bokeh
  - nglview
  - ipywidgets
  - scikit-learn
  - pip:
    - pip install git+https://github.com/KeithLabPitt/comp_alchemy.git
